spring:
  application.name: accreditation-api
  mvc.pathmatch.matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:yieldstreet}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  flyway:
    locations: classpath:db/migration
    enabled: true
  jpa:
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
        format_sql: true
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_BROKERS:localhost}
        bindings:
          producer-out-0:
            producer:
              configuration:
                value.serializer: com.yieldstreet.accreditation.audit.AccreditationStateChangeSerializer
      function:
        definition: producer
      bindings:
        producer-out-0:
          destination: ${KAFKA_TOPIC:accreditations}
          producer:
            use-native-encoding: true

server:
  port: ${HTTP_PORT:9999}
  forward-headers-strategy: framework
  error:
    include-message: always

logging:
  level:
    org.springframework.web: WARN
    org.hibernate: WARN
    org.apache: WARN

yieldstreet:
  accreditations:
    expire_confirmed_days: ${EXPIRE_CONFIRMED_DAYS:30}