version: "3.8"

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    container_name: zookeeper
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:3.3
    container_name: kafka
    ports:
      - "9093:9093"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://0.0.0.0:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper

  postgres:
    image: docker.io/postgres
    container_name: postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=yieldstreet
      - POSTGRES_USER=yieldstreet
      - POSTGRES_PASSWORD=password

  accreditation-api:
    image: com.yieldstreet/accreditation-api:1.0-SNAPSHOT
    pull_policy: never
    container_name: accreditation-api
    ports:
      - "9999:9999"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_NAME=yieldstreet
      - DB_USERNAME=yieldstreet
      - DB_PASSWORD=password
      - KAFKA_BROKERS=kafka:9092
      - KAFKA_TOPIC=accreditations
    depends_on:
      - postgres
      - kafka

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local