openapi: "3.0.0"
info:
  title: User Accreditation API
  description: Provides historical and real-time data reports.
  version: 1.0.0
paths:
  /user/accreditation:
    post:
      summary: Creates a new accreditation.
      operationId: createAccreditation
      tags:
        - admin
        - accreditations
      requestBody:
        description: An accreditation request.
        content:
          application/json:
            schema:
              $ref : "#/components/schemas/CreateAccreditationRequest"
      responses:
        200:
          description: Accreditation request was successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateAccreditationResponse'



components:
  schemas:
    CreateAccreditationRequest:
      type: object
      properties:
        user_id:
          type: string
        accreditation_type:
          type: string
          enum:
            - "BY_INCOME"
            - "BY_NET_WORTH"
        document:
          $ref: "#/components/schemas/Document"

    CreateAccreditationResponse:
      type: object
      properties:
        accreditation_id:
          type: string

    Document:
      type: object
      properties:
        name:
          type: string
        mime_type:
          type: string
        content:
          type: string


